[package]
name = "test_sst_importer"
version = "0.1.0"
edition = "2021"
publish = false
description = "test helpers for sst_importer"
license = "Apache-2.0"

[lib]
test = false

[dependencies]
crc32fast = "1.2"
engine_rocks = { workspace = true }
engine_traits = { workspace = true }
keys = { workspace = true }
kvproto = { workspace = true }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
grpcio = { workspace = true }
tempfile = "3.0"
futures = "0.3"
txn_types = { workspace = true }
external_storage ={ workspace = true }
tikv_util = { workspace = true }
